### ISSUE TITLE
Paper size/aspect ratio

### ISSUE THREAD

**Issue by MerlinMerlinMerlin1** [susiej/projectorview#3]
Is this program designed for a specific aspect ratio/paper size? Is there a way to set these? Also, it could be helpful to include a calibration grid with the program so we can confirm our calibration was correct. I really like the program and thanks for creating it. 

Also, I can create a pr if you like any of these ideas!

**Comment by susiej** [comment]
I’m unsure what you mean. How does paper size or aspect ratio come into it? The projector already tells the program the number of pixels it’s projecting so the user shouldn’t need to change that. And it can project any size pdf. The pdf tells the program how big the page is. We aren’t printing so paper size doesn’t matter. To use it the user should only need a tape measure (which I assume everyone who sews will own) and it shouldn’t need any extra knowledge.  There are a few bugs I have to iron out, which I’ll get around to when I have a break from work. The calibration grid is provided in the projectors for sewing Facebook group which is what I’ve used to test the program. I had considered drawing a grid in python but it won’t test that all the scaling is working correctly as you want the maths done on a real pdf. On 5 Mar 2023, at 1:33 am, MerlinMerlinMerlin1 ***@***.***> wrote:﻿
Is this program designed for a specific aspect ratio/paper size? Is there a way to set these? Also, it could be helpful to include a calibration grid with the program so we can confirm our calibration was correct. I really like the program and thanks for creating it.
Also, I can create a pr if you like any of these ideas!

**Comment by MerlinMerlinMerlin1** [comment]
That makes so much more sense! I hadn’t read the code yet so I was a bit fuzzy on implementation details. It works great and thanks for spending time on it!
